x-service_defaults: &service_defaults
  restart: no
  ipc: host
  tty: true
  volumes:
    - ./data:/src/data-out
  environment:
    OUTPUT_DIRECTORY: data-out
    DEEPL_API_KEY: "[ADD_YOUR_KEY_HERE]" # https://support.deepl.com/hc/de/articles/360020695820-Authentifizierungsschl%C3%BCssel
  logging:
    driver: "json-file"
    options:
      max-size: "100m"

# docker gpu settings to use gpu power. see: https://docs.docker.com/compose/gpu-support/
x-gpu: &gpu
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [ gpu ]


services:
  # Import and normalize the base data and prepare images for enrichment
  core-import:
    << : [*service_defaults]
    container_name: core-import
    image: xcurator/core-import:1.0.0-beta
    build:
      context: ./0-artefact-core-import

  # create visual embeddings (one each artefact record) based on the base64 image
  artefact-embedding:
    << : [*service_defaults,*gpu]
    container_name: artefact-embedding
    image: xcurator/artefact-embedding:1.0.0-beta
    build:
      context: ./1-artefact-embedding

  # segment image and extract the color palette of the foreground object based on the base64 image
  artefact-object-color:
    << : [*service_defaults,*gpu]
    container_name: artefact-object-color
    image: xcurator/artefact-object-color:1.0.0-beta
    build:
      context: ./1-artefact-object-color

  # translate titles and descriptions of artefacts into the target languages [de, en, nl]
  translation:
    << : [*service_defaults]
    container_name: translation
    image: xcurator/translation:1.0.0-beta
    build:
      context: ./1-translation

  # merge all enrichment outputs into a single dataset
  finalize:
    <<: [ *service_defaults ]
    container_name: finalize
    image: xcurator/finalize:1.0.0-beta
    build:
      context: ./3_finalize