server:
  port: 8082

spring:
  data:
    mongodb:
      username: ${MONGO_USERNAME:xcurator_mongo_user}
      password: ${MONGO_PASSWORD:xcurator_mongo_password}
      database: ${MONGO_DATABASE:xcurator}
      port: ${MONGO_PORT:27017}
      host: ${MONGO_HOST:localhost}
      auto-index-creation: true


#logging:
#  level:
#    org.springframework.boot.autoconfigure: DEBUG

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG